const ADD_NUMBER = 'ADD_NUMBER';
const SUB_NUMBER = 'SUB_NUMBER';
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const CHANGE_BANNERS = 'CHANGE_BANNERS';
const CHANGE_RECOMMENDS = 'CHANGE_RECOMMENDS';
const FETCH_HOME_MULTIDATA = 'FETCH_HOME_MULTIDATA';

export { ADD_NUMBER, SUB_NUMBER, INCREMENT, DECREMENT, CHANGE_BANNERS, CHANGE_RECOMMENDS, FETCH_HOME_MULTIDATA };
